# Generated by Django 2.0.6 on 2018-07-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantcard',
            options={'verbose_name': '商户卡', 'verbose_name_plural': '商户卡'},
        ),
        migrations.AlterModelOptions(
            name='merchantgroup',
            options={'verbose_name': '商户组', 'verbose_name_plural': '商户组'},
        ),
        migrations.AlterModelOptions(
            name='merchantuser',
            options={'verbose_name': '医院用户', 'verbose_name_plural': '医院用户'},
        ),
    ]
