# Generated by Django 2.0.6 on 2018-07-27 12:23

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180727_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontenduser',
            name='gender',
            field=django_fsm.FSMIntegerField(choices=[(0, '女'), (1, '男'), (2, '未知')], default=2),
        ),
    ]
