# Generated by Django 2.0.6 on 2018-07-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180727_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantuser',
            options={'permissions': (('mb_product_categories', '项目分类'), ('mb_all_products_list', '项目管理'), ('mb_products_recommended', '推荐项目'), ('mb_set_product_notice', '购买须知'), ('mb_order_list', '订单列表'), ('mb_order_retrieve', '订单详情'), ('mb_coupons_operation', '优惠券'), ('mb_sales_operation', '秒杀'), ('mb_groupon_operation', '拼团'), ('mb_assistance_operation', '砍价'), ('mb_order_stat', '销售统计'), ('mb_daily_user_stat', '用户统计'), ('mb_activity_data_stat', '活动统计'), ('mb_finance_stat', '财务统计'), ('mb_reservation_stat', '服务评分统计'), ('mb_index_page_banner', '首页banner'), ('mb_merchant_user_manage', '商户人员管理'), ('mb_merchant_index_page', '商户主页'), ('mb_merchant_card', '医院品牌'), ('mb_binding_wx_applet', '小程序绑定'), ('mb_wx_pay_auth', '微信支付授权'), ('mb_merchant_user_set_group', '用户分配角色')), 'verbose_name': '医院用户', 'verbose_name_plural': '医院用户'},
        ),
    ]
