# Generated by Django 2.0.6 on 2018-07-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180730_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantconfig',
            name='wx_mch_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='wxapp.WXMchUser', verbose_name='所属微信小程序商户'),
        ),
    ]
