# Generated by Django 2.0.6 on 2018-08-03 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180803_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantgroup',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
