# Generated by Django 2.0.6 on 2018-08-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180803_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantgroup',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='组名'),
            preserve_default=False,
        ),
    ]
