# Generated by Django 2.0.6 on 2018-07-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WXAppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('open_id', models.CharField(max_length=100, verbose_name='小程序用户唯一标识')),
                ('union_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='同公众号主体下唯一标识')),
                ('session_key', models.CharField(max_length=255, verbose_name='密钥')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('nick_name', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('avatar_url', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('gender', models.CharField(max_length=2, null=True, verbose_name='性别')),
                ('city', models.CharField(max_length=10, null=True, verbose_name='城市')),
                ('province', models.CharField(max_length=10, null=True, verbose_name='省份')),
                ('country', models.CharField(max_length=10, null=True, verbose_name='国家')),
                ('language', models.CharField(max_length=10, null=True, verbose_name='语言')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('pure_phone_number', models.CharField(max_length=20, null=True, verbose_name='区号的手机号')),
                ('country_code', models.CharField(max_length=5, null=True, verbose_name='区号')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WXMchUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('shop_id', models.CharField(max_length=100, verbose_name='小程序标识')),
                ('app_id', models.CharField(max_length=100, verbose_name='小程序id')),
                ('app_secret', models.CharField(max_length=100, verbose_name='小程序密钥')),
                ('mch_id', models.CharField(max_length=255, null=True, verbose_name='商户id')),
                ('access_token', models.CharField(max_length=255, null=True, verbose_name='接口调用凭证')),
                ('expires_in', models.IntegerField(default=0, verbose_name='凭证有效时间')),
                ('sign_key', models.CharField(max_length=255, null=True, verbose_name='签名算法key')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WXOrderRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('out_refund_no', models.CharField(max_length=255, verbose_name='商户退款单号')),
                ('refund_fee', models.IntegerField(verbose_name='退款金额')),
                ('refund_fee_type', models.CharField(max_length=255, verbose_name='货币种类')),
                ('refund_desc', models.CharField(max_length=255, null=True, verbose_name='退款原因')),
                ('refund_account', models.CharField(default='REFUND_SOURCE_RECHARGE_FUNDS', max_length=255, null=True, verbose_name='退款资金来源')),
                ('notify_url', models.CharField(max_length=255, null=True, verbose_name='退款结果通知url')),
                ('refund_id', models.CharField(max_length=255, null=True, verbose_name='微信退款单号')),
                ('cash_refund_fee', models.IntegerField(null=True, verbose_name='现金退款金额')),
                ('return_code', models.CharField(max_length=255, null=True, verbose_name='返回状态码')),
                ('return_msg', models.CharField(max_length=255, null=True, verbose_name='返回信息')),
                ('result_code', models.CharField(max_length=255, null=True, verbose_name='业务结果')),
                ('err_code', models.CharField(max_length=255, null=True, verbose_name='错误代码')),
                ('err_code_des', models.CharField(max_length=255, null=True, verbose_name='错误代码描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WXPaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('nonce_str', models.CharField(max_length=255, verbose_name='随机字符串')),
                ('sign', models.CharField(max_length=255, verbose_name='签名')),
                ('body', models.CharField(max_length=255, verbose_name='商品描述')),
                ('out_trade_no', models.CharField(max_length=255, verbose_name='商户订单号')),
                ('total_fee', models.IntegerField(verbose_name='标价金额')),
                ('spbill_create_ip', models.CharField(max_length=255, verbose_name='终端IP')),
                ('notify_url', models.CharField(max_length=255, verbose_name='通知地址')),
                ('trade_type', models.CharField(default='JSAPI', max_length=255, verbose_name='交易类型')),
                ('trade_state', models.CharField(choices=[(1, '支付成功'), (2, '转入退款'), (3, '未支付'), (4, '已关闭'), (5, '已撤销（刷卡支付）'), (6, '用户支付中'), (7, '支付失败(其他原因，如银行返回失败)')], default=3, max_length=50, null=True, verbose_name='交易状态')),
                ('sign_type', models.CharField(max_length=255, null=True, verbose_name='签名类型')),
                ('device_info', models.CharField(max_length=255, null=True, verbose_name='设备号')),
                ('detail', models.CharField(max_length=255, null=True, verbose_name='商品详情')),
                ('attach', models.CharField(max_length=255, null=True, verbose_name='附加数据')),
                ('fee_type', models.CharField(default='CNY', max_length=255, null=True, verbose_name='标价币种')),
                ('time_start', models.DateTimeField(max_length=255, null=True, verbose_name='交易起始时间')),
                ('time_expire', models.DateTimeField(max_length=255, null=True, verbose_name='交易结束时间')),
                ('goods_tag', models.CharField(max_length=255, null=True, verbose_name='订单优惠标记')),
                ('limit_pay', models.CharField(max_length=255, null=True, verbose_name='指定支付方式')),
                ('product_id', models.CharField(max_length=255, null=True, verbose_name='商品ID')),
                ('return_code', models.CharField(max_length=255, null=True, verbose_name='返回状态码')),
                ('return_msg', models.CharField(max_length=255, null=True, verbose_name='返回信息')),
                ('result_code', models.CharField(max_length=255, null=True, verbose_name='业务结果')),
                ('err_code', models.CharField(max_length=255, null=True, verbose_name='错误代码')),
                ('err_code_des', models.CharField(max_length=255, null=True, verbose_name='错误代码描述')),
                ('prepay_id', models.CharField(max_length=255, null=True, verbose_name='预支付标识')),
                ('code_url', models.CharField(max_length=255, null=True, verbose_name='二维码地址')),
                ('is_subscribe', models.CharField(max_length=255, null=True, verbose_name='是否关注公众账号')),
                ('bank_type', models.CharField(max_length=255, null=True, verbose_name='付款银行')),
                ('settlement_total_fee', models.IntegerField(null=True, verbose_name='应结订单金额')),
                ('cash_fee', models.IntegerField(null=True, verbose_name='现金支付金额')),
                ('cash_fee_type', models.CharField(max_length=255, null=True, verbose_name='现金支付货币类型')),
                ('transaction_id', models.CharField(max_length=255, null=True, verbose_name='微信支付订单号')),
                ('time_end', models.DateTimeField(max_length=255, null=True, verbose_name='支付完成时间')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.WXAppUser')),
                ('mch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.WXMchUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wxorderrefund',
            name='wx_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.WXPaymentOrder'),
        ),
        migrations.AddField(
            model_name='wxappuser',
            name='mch_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.WXMchUser'),
        ),
    ]
