# Generated by Django 2.0.6 on 2018-07-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_auto_20180721_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxorderrefund',
            name='wx_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='wxapp.WXPaymentOrder'),
        ),
    ]
