# Generated by Django 2.0.6 on 2018-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0004_auto_20180721_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxpaymentorder',
            name='trade_state',
            field=models.IntegerField(choices=[(1, '支付成功'), (2, '转入退款'), (3, '未支付'), (4, '已关闭'), (5, '已撤销（刷卡支付）'), (6, '用户支付中'), (7, '支付失败(其他原因，如银行返回失败)')], default=3, null=True, verbose_name='交易状态'),
        ),
    ]
