# Generated by Django 2.0.6 on 2018-07-24 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0005_auto_20180723_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='WXMchCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('cert_type', models.SmallIntegerField(blank=True, choices=[(1, '证书'), (2, '证书密钥')], null=True, verbose_name='证书类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wxmchuser',
            name='token_refresh_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='凭证更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wxmchcert',
            name='mch_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiclient_certs', to='wxapp.WXMchUser', verbose_name='商户'),
        ),
    ]
