# Generated by Django 2.0.6 on 2018-07-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0007_auto_20180725_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxmchuser',
            name='shop_id',
        ),
    ]
