# Generated by Django 2.0.6 on 2018-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0008_remove_wxmchuser_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxorderrefund',
            name='refund_channel',
            field=models.CharField(max_length=255, null=True, verbose_name='退款渠道'),
        ),
        migrations.AddField(
            model_name='wxorderrefund',
            name='refund_recv_accout',
            field=models.CharField(max_length=255, null=True, verbose_name='退款入账账户'),
        ),
        migrations.AddField(
            model_name='wxorderrefund',
            name='refund_request_source',
            field=models.CharField(max_length=255, null=True, verbose_name='退款发起来源'),
        ),
        migrations.AddField(
            model_name='wxorderrefund',
            name='refund_status',
            field=models.IntegerField(choices=[(1, '退款成功'), (2, '退款异常'), (3, '退款关闭')], default=3, null=True, verbose_name='退款状态'),
        ),
        migrations.AddField(
            model_name='wxorderrefund',
            name='refund_success_time',
            field=models.DateTimeField(null=True, verbose_name='退款成功时间'),
        ),
        migrations.AddField(
            model_name='wxorderrefund',
            name='settlement_refund_fee',
            field=models.IntegerField(null=True, verbose_name='退款金额'),
        ),
        migrations.AddField(
            model_name='wxorderrefund',
            name='success_time',
            field=models.DateTimeField(null=True, verbose_name='退款成功时间'),
        ),
    ]
