# Generated by Django 2.0.6 on 2018-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0009_auto_20180728_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxorderrefund',
            name='refund_status',
            field=models.IntegerField(choices=[(1, '退款成功'), (2, '退款异常'), (3, '退款处理中'), (4, '退款关闭')], default=4, null=True, verbose_name='退款状态'),
        ),
    ]
