# Generated by Django 2.0.6 on 2018-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0010_auto_20180728_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxmchuser',
            name='app_review_result',
            field=models.CharField(max_length=255, null=True, verbose_name='小程序审核结果'),
        ),
        migrations.AddField(
            model_name='wxmchuser',
            name='app_review_status',
            field=models.IntegerField(choices=[(1, '审核成功'), (2, '审核失败'), (3, '审核中')], null=True, verbose_name='小程序审核状态'),
        ),
        migrations.AddField(
            model_name='wxmchuser',
            name='app_reviewed_at',
            field=models.DateTimeField(null=True, verbose_name='小程序审核时间'),
        ),
        migrations.AddField(
            model_name='wxmchuser',
            name='app_submitted_at',
            field=models.DateTimeField(null=True, verbose_name='小程序提交时间'),
        ),
        migrations.AddField(
            model_name='wxmchuser',
            name='app_version',
            field=models.CharField(max_length=255, null=True, verbose_name='小程序版本'),
        ),
    ]
