# Generated by Django 2.0.6 on 2018-07-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0012_wxmchuser_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxorderrefund',
            name='refund_fee',
            field=models.IntegerField(null=True, verbose_name='退款金额'),
        ),
        migrations.AlterField(
            model_name='wxorderrefund',
            name='refund_fee_type',
            field=models.CharField(max_length=255, null=True, verbose_name='货币种类'),
        ),
    ]
