# Generated by Django 2.0.6 on 2018-08-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0013_auto_20180731_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxmchuser',
            options={'verbose_name': '小程序商家用户', 'verbose_name_plural': '小程序商家用户'},
        ),
    ]
